name: Django CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: django_user
          POSTGRES_PASSWORD: django_pass
          POSTGRES_DB: django_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U django_user -d django_db"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      # Подключение Django к PostgreSQL
      PGHOST: 127.0.0.1
      PGUSER: django_user
      PGPASSWORD: django_pass
      PGDATABASE: django_db
      PGPORT: 5432
      CI: true

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Upgrade pip
      run: python -m pip install --upgrade pip

    - name: Install dependencies
      run: pip install -r stocks_products/requirements.txt

    - name: Wait for Postgres to be ready
      run: |
        until pg_isready -h $PGHOST -U $PGUSER -d $PGDATABASE; do
          echo "Waiting for Postgres..."
          sleep 1
        done

    - name: Run migrations
      run: python stocks_products/manage.py migrate

    - name: Run tests
      run: python stocks_products/manage.py test --verbosity=2
